### ISSUE TITLE
여기서 진행되지가 않는데 어떻게 해야 하나요?

### ISSUE THREAD

**Issue by cks0773** [ChangjunChrisLee/DataBaseClass#1]
<img width="661" alt="주석 2020-09-04 164131" src="https://user-images.githubusercontent.com/70746254/92215009-26834700-eecf-11ea-8b5d-4d56db5c7396.png">
영상보고 여기까지 따라왔는데 다음단계로 넘어가지지가 않네요

**Comment by jaehoonkimm** [comment]
먼저 mysql의 path 설정을 완료 하셨을까요? 1주차 영상(DB1) 33분~ 부터 나오는 Path 추가 내용이 정상적으로 완수되지 않으면 해당 문제가 발생할 수 있습니다. 또한, Path 추가시에 오타가 발생하였을 경우에도 정상적으로 해결이 되지 않을 수 있습니다.
Path 부분을 잘 따라하셨음에도 불구하고 동일한 오류가 계속 발생한다면, 
명령어 mysql -u root -p 앞에 ".\"를 추가하여
.\mysql -u root -p
위와 같은 명령어로 시도해보신후, 해결 유무를 다시 알려주세요!

**Comment by cks0773** [comment]
<img width="654" alt="주석 2020-09-04 172432" src="https://user-images.githubusercontent.com/70746254/92218096-8d0a6400-eed3-11ea-91af-93b985f7e2c9.png">
path설정 오타없이 완료하고 명령어 다르게시도해봤는데도 안되네요
다 삭제하고 처음부터 다시해보겠습니다..

**Comment by jaehoonkimm** [comment]
올려주신 캡쳐 화면으로 보아, 맨 처음 입력된 Path를 설정하는 과정에서 문제가 있는 것 같습니다. 일단 위 에러메시지를 보면, Path를 등록하는 과정이 정상적으로 수행되지 않고 있습니다. 아마도 경로[폴더의 위치, 폴더의 이름 등] 문제인 것 같은데요.

우선, setx path 명령어 뒤에 입력한 C:\Program Files\MySQL\MySQL Server 8.0\bin 경로(폴더)가 실제로 존재하지 않으면, 해당 명령어가 작동하지 않습니다. 
파일 탐색기를 통해 C 드라이브 안에 Program Files->MySQL->MySQL Server 8.0->bin 이 폴더들이 차례로 존재하는지 확인한 후에, 만약 C 드라이브 안에 해당 폴더가 없거나, 이름이 다르다면 실제 존재하는 폴더의 이름으로 바꿔서 저 명령어를 실행해주셔야 합니다.

즉, 만약 본인의 컴퓨터에 설치된 MySQL의 경로 중 일부가 위 명령어와 다른 경우, 실제 컴퓨터에 존재하는 경로로 적어서 명령어를 실행해야합니다.
[예시 : MySQL Server 8.0이 아니라 실제로 컴퓨터에는 MySQL Server 7.0으로 되어 있는 경우,
명령어를 7.0으로 입력해야 함]

파일 탐색기를 통해 MySQL 서버가 설치된 폴더를 찾아주시고, 최종적으로 명령어 안에 입력하는 경로의 마지막 부분이 ~~~~~bin" /m 과 같은 형태로 끝나도록 입력해주셔야 합니다.

**Comment by jaehoonkimm** [comment]
Path 등록 명령이 정상적으로 수행된 경우, 붉은색 오류 메시지(~~~~이름을 확인하고, 경로가 올바른지 검증한 다음 다시 시도하십시오.~~~)가 뜨는 것이 아닌, 
[성공: 지정한 값을 저장했습니다.] 메시지가 나오게 됩니다.

**Comment by cks0773** [comment]
처음 시도했을때는 "지정한 값을 저장했습니다"라는 문구가 떴었습니다. 한번 더 시도하니 저렇게 뜨네요. 
폴더 문제인가 싶어서 확인했는데 폴더도 문제가 없습니다.
다시 삭제하고 처음부터 진행했는데도 오류가 뜨네요.

**Comment by jaehoonkimm** [comment]
https://dog-developers.tistory.com/21
일단 위 링크의 방법을 사용하여 환경변수를 추가하는 방법을 시도해보시면 좋을 것 같습니다. 해당 방법을 통해 환경변수 Path 설정을 해보신 후, 여전히 문제 해결이 되지 않는다면 다시 코멘트 부탁드립니다.

**Comment by cks0773** [comment]
문제 해결됬습니다! 감사합니다!

**Comment by jaehoonkimm** [comment]
해결되어서 다행입니다! 본 Issue는 Close 버튼을 눌러서 종결 처리 부탁드립니다! 감사합니다 :)
