### ISSUE TITLE
연결 오류

### ISSUE THREAD

**Issue by cks0773** [ChangjunChrisLee/DataBaseClass#2]
<img width="960" alt="sds" src="https://user-images.githubusercontent.com/70746254/94111189-ac673200-fe7e-11ea-906f-9772a9ac7592.png">
mysql을 실행하니 이런오류가 뜹니다.
전에 한번이런적이 있어서 삭제했다가 다시 깔아서 해결했었는데 또 다시 오류가 뜨네요.
작업관리자에서 mysql서비스 중지되어있던걸 실행시키는 방법은 해봤습니다. .도움 부탁드려요!

**Comment by jaehoonkimm** [comment]
해당 오류는 Workbench의 사용과 별개로, MySQL이 활성화되지(켜지지) 않아서 발생하는 문제로 추정됩니다.
먼저, MySQL이 설치된 폴더로 접근하셔서
[c:\mysql 또는 c:\ProgramData\mysql]
[c:\mysql\bin 또는 c:\ProgramData\mysql\bin]

위 폴더 안의 (mysql.exe) 파일을 실행해본 후, workbench를 다시 종료 후 켜보시면 될 것 같습니다.

해당 방법으로 해결이 되지 않으시면 다시 코멘트 주세요!

**Comment by cks0773** [comment]
안됩니다!..

**Comment by jaehoonkimm** [comment]
https://m.blog.naver.com/dlwoen9/220544478535

혹시 위 주소의 방법을 통해 사용자 권한을 재설정 한 후, 시도해보실 수 있으실까요? 위 방법으로도 해결 되지 않으시면 다시 코멘트 부탁드립니다!

**Comment by cks0773** [comment]
<img width="960" alt="dfgvrvrgweg" src="https://user-images.githubusercontent.com/70746254/94161938-2ae4c380-fec1-11ea-8fcf-69c22005cbf6.png">
이렇게뜨네요

**Comment by cks0773** [comment]
삭제하고 처음부터 다시해보겠습니다. 답변해주셔셔 감사합니다!
